server:
  port: 9090

spring:
  application:
    name: auth-service
  datasource:
    url: jdbc:postgresql://localhost:5440/authw
    username: postgres
    password: 7482040607
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  secret: rE0kkGwPG8QzqawkOUbLOUlkv/wEwZkLtS1nRmnkSHKInyfl3DVrzSCfTsOTYUBaChQK0rlP3waWT43QW/Fzug==
  expiration: 900000 # 15 min
  refreshExpiration: 1296000000  # 15 days
